### ISSUE TITLE
the bias of visible layer

### ISSUE THREAD

**Issue by SunnyMarkLiu** [meownoid/tensorfow-rbm#1]
Hi, you did awesome job! 
But I'm a little confused about the bias of visible layer which is returned by `W, Bv, Bh = rbm.get_weights()`, sometime I often see bias of hidden layer, what is the bias of input/visible layer? thx!
best wishes!
SunnyMarkLiu

**Comment by meownoid** [comment]
RBM is a bidirectional network. So, at first we compute hidden representation of input data as follows:
```
hidden_data = s1(input_data @ W + hidden_bias)
```
After that, we should reconstruct input data from this hidden representation with the same `W` matrix, but obviously with different bias (because of different dimensionalities):
```
data_reconstructed = s2(hidden_data @ W.T + visible_bias)
```
And now we can compute all updates.

See also original paper:
https://www.cs.toronto.edu/~hinton/absps/guideTR.pdf
Equations (7) and (8). Visible and hidden biases are denoted as `a` and `b` respectively.

**Comment by meownoid** [comment]
**Note**: when RBM's weights is used for deep network initialization, visible bias should be ignored.

**Comment by SunnyMarkLiu** [comment]
Thank you very much!
